# Generated by Django 4.2.7 on 2023-11-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default="placeholder", max_length=255)),
                ("lastname", models.CharField(default="placeholder", max_length=255)),
                ("nickname", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point_p1", models.IntegerField(null=True)),
                ("point_p2", models.IntegerField(null=True)),
                (
                    "player_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player_data.player_data",
                        to_field="nickname",
                    ),
                ),
            ],
        ),
    ]
