# Generated by Django 4.2.7 on 2023-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player_data",
            name="firstname",
            field=models.CharField(default="placeholder", max_length=255),
        ),
        migrations.AddField(
            model_name="player_data",
            name="lastname",
            field=models.CharField(default="placeholder", max_length=255),
        ),
    ]
