# Generated by Django 5.0 on 2023-12-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player_one",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="player_data.player_data",
            ),
        ),
    ]
