# Generated by Django 4.2.7 on 2023-11-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_data", "0002_player_data_firstname_player_data_lastname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point_p1", models.IntegerField(null=True)),
                ("point_p2", models.IntegerField(null=True)),
            ],
        ),
    ]
