# Generated by Django 5.0 on 2023-12-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_data", "0002_alter_game_player_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="player_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_two",
                to="player_data.player_data",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_one",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_one",
                to="player_data.player_data",
            ),
        ),
    ]
