# Generated by Django 4.2.7 on 2023-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_data", "0003_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="player_1",
            field=models.ManyToManyField(to="player_data.player_data"),
        ),
    ]
