# Generated by Django 4.2.7 on 2023-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_data", "0003_game_player_two_alter_game_player_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="player_data",
            name="email",
            field=models.CharField(default="placeholder", max_length=255),
        ),
    ]
