# Generated by Django 4.2.7 on 2023-11-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_data", "0004_game_player_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="player_1",
        ),
        migrations.AddField(
            model_name="game",
            name="player_one",
            field=models.ManyToManyField(
                related_name="player1", to="player_data.player_data"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_two",
            field=models.ManyToManyField(
                related_name="player2", to="player_data.player_data"
            ),
        ),
    ]
