version: '3.9'

services:
  # React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    networks:
      - netpong
    command: pnpm vite --port ${FRONT_PORT} --host

  # NestJs
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - netpong

  # PostgreSQL
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - netpong
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    #volumes:
    # - postgres:/var/lib/postgresql/data

  # Volumes
  #volumes:
  #  postgres:

  # Networks
networks:
  netpong:
    driver: bridge
