version: "3.8"

services:
  django:
    container_name: django
    build:
      context: ./django
      args:
        DOMAIN:
    env_file: .env
    ports:
      - "443:443"
      - "80:80"
    networks:
      - my-network
    volumes:
      - static:/ftt/ftt/static
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file: .env
    container_name: $POSTGRES_HOST
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  static:
  db-data:


networks:
  my-network:
    driver: bridge
