version: "3.8"

services:
  caddy:
    image: caddy
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my-network
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - static:/static
      - media:/media
      - ssl:/ssl
    restart: unless-stopped

  django:
    build:
      context: ./django
      args:
        DOMAIN:
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - my-network
    volumes:
      - static:/ftt/static
      - media:/ftt/media
      - ssl:/ssl
    depends_on:
      - db
      - caddy
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file: .env
    container_name: $POSTGRES_HOST
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ssl:
  media:
  static:
  db-data:


networks:
  my-network:
    driver: bridge