version: '3.9'

services:

  # NestJs - NodeJs
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    networks:
      - netpong

  # PostgresSql - Database
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_DB_FILE: /run/secrets/pg_database
      #DB_INIT_ARGS_FILE="/run/secrets/db_init_args"
    secrets:
      - pg_password
      - pg_user
      - pg_database
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - netpong
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

secrets:
  pg_user:
  pg_password:
  pg_database:
  ft_api_id:
    external: true
  ft_api_secret:
    external: true

# Volumes
volumes:
  postgres:

    # Networks
networks:
  netpong:
    driver: bridge
