version: '3.8'

services:
  frontend:
    build:
      context: ..
      args:
            VARIANT: 18
      dockerfile: .devcontainer/frontend/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    env_file: devcontainer.env
    #entrypoint: pnpm vite

  backend:
    build:
      context: ..
      dockerfile: .devcontainer/backend/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    env_file: devcontainer.env
    command: sleep infinity
    network_mode: service:db
    entrypoint: python manage.py runserver

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
